apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
   kubernetes.io/change-cause: "first version"
  name: deployment-test-2
  labels:
    app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      name: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
   app: backend
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80