apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: cont-mypod
    image: nginx
---    
apiVersion: v1
kind: Pod
metadata:
  name: my-pod2
spec:
  containers:
  - name: cont-mypod2
    image: nginx